# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Obsidian Notes"	# changed
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: dcpetty
github_username: dcpetty
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "David C. Petty"	# changed
  avatar : "/assets/images/monty-192x192.png"	# changed
  bio    : "The public <a href=\"https://obsidian.md/\">Obsidian</a> notes <a href=\"https://jekyllrb.com/\">Jekyll</a> website of <a href=\"http://github.com/dcpetty/obsidian/\"><code>dcpetty</code></a>."	# changed
  links: # All links changed.
    - label: "Cambridge (MA)"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://google.com/maps/place/Cambridge,+MA/"
      # url: "https://cambridgema.gov/~/media/Files/GIS/allmapsandatlases/CambridgeBaseMap18x24.pdf"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dcpetty.dev/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dcpetty/obsidian"
    - label: "CV"
      icon: "fas fa-fw fa-info"
      url: "https://dcpetty.dev/cv"
    - label: "LinkedIn"	# added
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/dcpetty"
    - label: "stack<strong>overflow</strong>"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/17467335"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sprytechdatadevil"
    - label: "Bluesky" # added (color #3a83f7)
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/dcpetty.bsky.social"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/dcpetty"
    - label: "BY-NC-SA"
      icon: "fab fa-fw fa-creative-commons"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

footer:
  links: # All links changed.
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dcpetty.dev/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dcpetty/obsidian"
    - label: "CV"
      icon: "fas fa-fw fa-info"
      url: "https://dcpetty.dev/cv"
    - label: "BY-NC-SA"
      icon: "fab fa-fw fa-creative-commons"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Added
baseurl: /obsidian
